In [1]:
import pandas as pd

In [44]:
hdi_df = pd.read_csv('../data-sources/Human Development Index - Full.csv')
imf_gdp_df = pd.read_csv('../data-sources/imf-gdp.csv')

min_year = 2015

In [46]:
column_list = [col for col in hdi_df.columns if col.startswith('Human Development Index (') and int(col.replace(')', '').replace('Human Development Index (', '')) >= min_year]
column_list = ['Country'] + column_list

hdi_clean_df = hdi_df[column_list].dropna()
clean_df_columns = hdi_clean_df.columns
clean_df_columns = [col.replace(')', '').replace('Human Development Index (', '') for col in clean_df_columns]
hdi_clean_df.columns = clean_df_columns
hdi_clean_df.reset_index(drop=True, inplace=True)
hdi_clean_df

                  Country   2015   2016   2017   2018   2019   2020   2021
0             Afghanistan  0.478  0.481  0.482  0.483  0.488  0.483  0.478
1                  Angola  0.582  0.596  0.597  0.595  0.595  0.590  0.586
2                 Albania  0.795  0.798  0.802  0.806  0.810  0.794  0.796
3                 Andorra  0.867  0.871  0.868  0.872  0.873  0.848  0.858
4    United Arab Emirates  0.865  0.870  0.897  0.909  0.920  0.912  0.911
..                    ...    ...    ...    ...    ...    ...    ...    ...
185                 Samoa  0.716  0.717  0.716  0.716  0.715  0.712  0.707
186                 Yemen  0.477  0.467  0.459  0.459  0.461  0.460  0.455
187          South Africa  0.716  0.719  0.720  0.726  0.736  0.727  0.713
188                Zambia  0.562  0.564  0.568  0.572  0.575  0.570  0.565
189              Zimbabwe  0.582  0.588  0.594  0.602  0.601  0.600  0.593

[190 rows x 8 columns]

In [50]:
imf_gdp_df.rename(columns={'GDP, current prices (Billions of U.S. dollars)': 'Country'}, inplace=True)
column_list = ['Country'] + [col for col in imf_gdp_df.columns if col != 'Country' and int(col) >= min_year]
column_list
clean_imf_gdp_df = imf_gdp_df[column_list].dropna()
clean_imf_gdp_df = clean_imf_gdp_df[clean_imf_gdp_df.isin(['no data']).any(axis=1) == False]
clean_imf_gdp_df.reset_index(drop=True, inplace=True)
clean_imf_gdp_df

['Country',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 '2026',
 '2027',
 '2028',
 '2029']